server:
  port: 2021
#  serverTimeZone=UTC&
spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/showgrade?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: log4j,stat,wall
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    port: 6379
    host: localhost

mybatis:
  type-aliases-package: com.xuexikuaile.deng.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#logging:
#  file:
#    name: spring-boot.log
#  pattern:
#    console: "%d{yyyy-MM-dd} [ %thread ] - [ %-5level ] [ %logger{50} : %line ] - %msg%n"
#    file: "%d{yyyy-MM-dd} [ %thread ] - [ %-5level ] [ %logger{50} : %line ] - %msg%n"
